# Generated by Django 3.0.4 on 2020-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('Ngo_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('Address', models.TextField(max_length=100, null=True)),
                ('Contact_No', models.TextField(null=True)),
                ('Email_ID', models.EmailField(max_length=254, null=True)),
                ('Website', models.CharField(max_length=100, null=True)),
                ('Found_by', models.CharField(max_length=100, null=True)),
                ('Comments', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
