# Generated by Django 3.0.4 on 2020-03-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO_HOME', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='Comments',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='Found_by',
            new_name='Domain',
        ),
    ]
